_wandb:
    value:
        cli_version: 0.21.0
        e:
            hx0iy20rnjz76c96pvkwn77r9dp9ptfa:
                apple:
                    ecpuCores: 2
                    gpuCores: 14
                    memoryGb: 16
                    name: Unknown
                    pcpuCores: 6
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "3221225472"
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "425887469568"
                email: sis000419@gmail.com
                executable: /usr/local/Caskroom/miniconda/base/envs/auta_dist/bin/python
                git:
                    commit: 17d92604d39f05f2139ab61943c2607c535ae7ae
                    remote: https://github.com/outSeop/auta_dist.git
                host: inssongs-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-10.16-x86_64-i386-64bit
                program: /Users/song-inseop/dev/auta_colab/main.py
                python: CPython 3.11.0
                root: /Users/song-inseop/dev/auta_colab
                startedAt: "2025-08-08T16:51:29.111592Z"
                writerId: hx0iy20rnjz76c96pvkwn77r9dp9ptfa
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.11.0
            "5": 0.21.0
            "8":
                - 2
            "12": 0.21.0
            "13": darwin-x86_64
method:
    value: knowledge_distillation
student:
    value: yolov11s
task:
    value: figma_ui_detection
teacher:
    value: yolov11l
