_wandb:
    value:
        cli_version: 0.21.1
        e:
            8mrra3dewjr9u4zhn9jr4tfeo8li98cr:
                apple:
                    ecpuCores: 2
                    gpuCores: 14
                    memoryGb: 16
                    name: Unknown
                    pcpuCores: 6
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "4294967296"
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "417502875648"
                email: sis000419@gmail.com
                executable: /usr/local/Caskroom/miniconda/base/envs/yolo-distill/bin/python
                git:
                    commit: 17d92604d39f05f2139ab61943c2607c535ae7ae
                    remote: https://github.com/outSeop/auta_dist.git
                host: inssongs-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-10.16-x86_64-i386-64bit
                program: /Users/song-inseop/dev/auta_colab/main.py
                python: CPython 3.11.13
                root: /Users/song-inseop/dev/auta_colab
                startedAt: "2025-08-08T18:03:57.946885Z"
                writerId: 8mrra3dewjr9u4zhn9jr4tfeo8li98cr
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
                - 61
            "4": 3.11.13
            "5": 0.21.1
            "8":
                - 2
            "12": 0.21.1
            "13": darwin-x86_64
method:
    value: knowledge_distillation
student:
    value: yolov11s
task:
    value: figma_ui_detection
teacher:
    value: yolov11l
